[default]
src = 'src'
out = 'out'
libs = ['lib']

solc = "0.8.10"
bytecode_hash = "none"
optimizer_runs = 1000000

[intense]
fuzz_runs = 10000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config